import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    modalContent: {
        width: '80%',
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 20,
        elevation: 5,
        marginVertical: 20,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalTitle: {
        textAlign: 'center',
        fontSize: 24,
        fontWeight: 'bold',
        marginTop: 30,
        marginBottom: 30,
        color: '#555',
    },
    closeButtonReviews: {
        position: 'absolute',
        top: 0,
        right: 0,
        borderRadius: 15,
        width: 60,
        height: 60,
    },
    nutritionContainer: {
        padding: 20,
        backgroundColor: '#fff',
        borderRadius: 10,
        elevation: 3,
        borderColor: '#ddd',
        borderWidth: 1,
        marginBottom: 20,
    },
    per100gLabel: {
        position: 'absolute',
        top: -20,
        left: 20,
        padding: 5,
        backgroundColor: '#f8f8f8',
        width: 90,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#ddd',
    },
    caloriesContainer: {
        backgroundColor: '#f8f8f8',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#ddd',
        marginHorizontal: 100,
        borderBottomWidth: 0,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
    },
    macroValue: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    macroLabel: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#666',
    },
    fullWidth: {
        width: '100%',
    },
    addMealText: {
        color: '#555',
        textAlign: 'center',
        marginTop: 30,
        fontSize: 20,
        width: '100%',
    },
    macroRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 15,
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 10,
        backgroundColor: '#f8f8f8',
    },
    macroColumn: {
        alignItems: 'center',
    },
});
