services:
  - type: web
    name: fithub-backend
    runtime: docker
    region: frankfurt
    repo: https://github.com/Gjxrgj/FitHub
    branch: main
    plan: free
    autoDeploy: true
    dockerContext: ./FitHubAPI
    dockerfilePath: ./FitHubAPI/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: fithub-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: fithub-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: fithub-db
          property: password
      - key: STRIPE_API_KEY
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI
        value: https://fithub-backend.onrender.com/login/oauth2/code/google
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_AUTHORIZATION_GRANT_TYPE
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_NAME
        sync: false


databases:
  - name: fithub-db
    plan: free
    region: frankfurt
    postgresMajorVersion: 15
