services:
  - type: web
    name: fithub-backend
    runtime: docker
    repo: https://github.com/Gjxrgj/FitHub
    branch: main
    plan: free
    autoDeploy: true
    dockerContext: ./FitHubAPI
    dockerfilePath: ./FitHubAPI/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: fithub-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: fithub-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: fithub-db
          property: password
      - key: STRIPE_API_KEY
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: fithub-db
    plan: free
    postgresMajorVersion: 15
