services:
  - type: web
    name: fithub-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/FitHubAPI-0.0.1-SNAPSHOT.jar
    rootDir: FitHubAPI
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: fithub-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: fithub-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: fithub-db
          property: password
databases:
  - name: fithub-db
    plan: free
    postgresMajorVersion: 15
