import {StyleSheet} from 'react-native';
import {theme} from '../../theme/theme.ts';


export const styles = StyleSheet.create({
    sectionTitle: {
        fontSize: 20,
        color: theme.colors.primary,
        marginBottom: 15,
    },
    contactInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    profileHeader: {
        alignItems: 'center',
        marginBottom: 40,
        marginTop: 30,
    },
    shadowContainer: {
        borderRadius: 50,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 1,
        shadowRadius: 15,
        elevation: 10,
    },
    name: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#555',
    },
    starsContainer: {
        flexDirection: 'row',
        marginTop: 5,
    },
    contactContainer: {
        padding: 20,
        backgroundColor: '#f9f9f9',
        borderRadius: 10,
        marginBottom: 20,
        elevation: 2,
    },
    contactText: {
        fontSize: 16,
        color: '#555',
        marginLeft: 10,
    },
    personalTrainingText: {
        fontSize: 16,
        color: '#555',
    },
    descriptionContainer: {
        padding: 20,
        backgroundColor: theme.colors.background,
        borderRadius: 10,
        marginBottom: 20,
        elevation: 2,
    },
    imageContainer: {
        padding: 20,
        backgroundColor: theme.colors.background,
        borderRadius: 10,
        marginBottom: 20,
        elevation: 2,
    },
    fullImage: {
        width: '100%',
        height: 500,
        resizeMode: 'contain',
    },
    descriptionText: {
        fontSize: 16,
        color: '#555',
    },
    promotionToggle: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 15,
        backgroundColor: theme.colors.background,
        borderRadius: 10,
        elevation: 1,
        marginBottom: 10,
    },
    promotionsContainer: {
        padding: 15,
        backgroundColor: theme.colors.background,
        borderRadius: 10,
        elevation: 1,
        marginBottom: 10,
    },
    promotion: {
        marginVertical: 10,
        padding: 15,
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 10,
    },
    promotionText: {
        fontSize: 14,
        color: '#555',
    },
    reviewButton: {
        alignSelf: 'center',
        marginBottom: 20,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        width: '80%',
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 20,
        elevation: 5,
        marginVertical: 20,
    },
    modalForImageContent: {
        width: '80%',
    },
    reviewStars: {
        justifyContent: 'flex-end',
    },
    modalTitle: {
        textAlign: 'center',
        fontSize: 24,
        fontWeight: 'bold',
        marginTop: 10,
        marginBottom: 30,
    },
    review: {
        marginVertical: 10,
    },
    reviewRating: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    reviewComment: {
        fontSize: 14,
        color: '#555',
    },
    closeButton: {
        marginTop: 20,
    },
    closeButtonImage: {
        position: 'absolute',
        top: 20,
        right: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        borderRadius: 15,
        padding: 5,
    },
    prevButton: {
        position: 'absolute',
        top: '50%',
        left: 20,
        transform: [{translateY: -50}],
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        borderRadius: 15,
        padding: 10,
    },
    nextButton: {
        position: 'absolute',
        top: '50%',
        right: 20,
        transform: [{translateY: -50}],
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        borderRadius: 15,
        padding: 10,
    },
    defaultIconContainer: {
        backgroundColor: '#eee',
        justifyContent: 'center',
        alignItems: 'center',
    },
    pricingContainer: {
        padding: 20,
        backgroundColor: '#f9f9f9',
        borderRadius: 10,
        marginBottom: 20,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#ddd',
    },
    priceItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    priceItemGroupTraining: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 30,
    },
    pricingText: {
        fontSize: 16,
        color: '#555',
        fontWeight: '600',
    },
    priceValue: {
        fontSize: 16,
        color: theme.colors.primary,
        fontWeight: 'bold',
    },
    thumbnail: {
        width: 100,
        height: 100,
        margin: 5,
    },
    closeButtonReviews: {
        position: 'absolute',
        top: 0,
        right: 0,
        borderRadius: 15,
        width: 60,
        height:60,
    },
    imageSectionTitleButton: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    editIconContainer: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: theme.colors.primary,
        borderRadius: 20,
        padding: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
});
