spring.application.name=UserService

server.port=8081

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/UserServiceDatabase
spring.datasource.username=
spring.datasource.password=

# Hibernate (JPA) Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool Configuration (Optional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

#Google authentication
spring.security.oauth2.client.registration.google.client-id=269397918020-59nklc57s5fhm6aantomar2djtmiilhm.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=google

